-- AlterTable
ALTER TABLE "user" ADD COLUMN     "frases" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "precicion_global" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tiempo_promedio" DOUBLE PRECISION NOT NULL DEFAULT 0;
